# Should only be used in a job where MATLAB and MatBox is installed in previous steps

name: 'Check code and upload report'
description: 'Analyse code for code issues and upload code issues report to GitHub'

inputs:
  code_directory:
    description: 'Which folder to run the code check on'
    required: false
    default: './code'
  tools_directory:
    description: 'Where the codecheckToolbox function is located'
    required: false
    default: './tools'

runs:
  using: "composite"
  steps:
    - name: Check if buildfile exists
      id: check-buildfile
      shell: bash
      run: |
        if [ -f "buildfile.m" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Check for MATLAB code issues (buildtool)
      if: steps.check-buildfile.outputs.exists == 'true'
      uses: matlab-actions/run-build@v2
      with:
        tasks: check

    - name: Check for MATLAB code issues
      if: steps.check-buildfile.outputs.exists != 'true'
      uses: matlab-actions/run-command@v2
      with:
        command: |
          addpath(genpath("${{ inputs.tools_directory }}"));
          if exist("codecheckToolbox", "file")
            codecheckToolbox();
          else
            matbox.tasks.codecheckToolbox(pwd, ...
              "FoldersToCheck", "${{ inputs.code_directory }}");
          end

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      continue-on-error: true # Will fail for MATLAB release < R2023a
      with:
        sarif_file: docs/reports/code_issues.sarif
