# NB: Will only process "skip" and "ignore-words-list" from the codespell 
# config file if provided

name: Run Codespell

on:
  push:
    branches: [ $default-branch ]
    
  pull_request:
    branches: [ $default-branch ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  reuse-workflow-run-codespell:
    name: Run Codespell
    uses: ehennestad/matbox/.github/workflows/reusable_run_codespell.yml@v0.9
    with:
      # Specify the path of a codespell config file relative to the repository 
      # root directory
      config_file: .codespellrc
