name: 'Push GitHub badges'
description: 'Push badges for use on GitHub and located in .github/badges if there are detected changes.'

runs:
  using: "composite"
  steps:
      # Commit updated SVG badges for the issues and tests (if changed)
      - name: Commit SVG badges if updated
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch 

          if [[ $(git add .github/badges/* --dry-run | wc -l) -gt 0 ]]; then
            git add .github/badges/*
            git commit -m "Update GitHub badges"
            git push -f
          else
            echo "Nothing to commit"
          fi
