name: 'Install MatBox'
description: 'Install MatBox in MATLAB on GitHub runner'
inputs:
  mode:  # mode of installation: release or commit, i.e install latest released version or use latest commit
    description: 'Which installation mode to use'
    required: true
    default: 'release'
runs:
  using: "composite"
  steps:
      - name: Show current work dir
        shell: bash
        run: pwd

      - name: List current work dir
        shell: bash
        run: ls

      - name: Install MatBox
        uses: matlab-actions/run-command@v2
        with:
          command: |
            installMatBox( "${{ inputs.mode }}", "InstallationLocation", "/home/runner/" )
