# Should only be used in a job where MATLAB and MatBox is installed in previous steps

name: 'Run toolbox test suites'
description: 'Run the test suites available for a MATLAB toolbox'

inputs:
  code_directory:
    description: 'Which folder to run the tests on'
    default: './code'
  tools_directory:
    description: 'Where the testToolbox function is located'
    default: './tools'

runs:
  using: "composite"
  steps:
    - name: Run MATLAB test suites
      uses: matlab-actions/run-command@v2
      if: always()
      with:
        command: |
          addpath(genpath("${{ inputs.tools_directory }}"));
          if exist("testToolbox", "file")
            testToolbox();
          else
            matbox.tasks.testToolbox(pwd, ...
                "SourceFolderName", "${{ inputs.code_directory }}", ...
                "ToolsFolderName", "${{ inputs.tools_directory }}");
          end

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: "docs/reports/test-results.xml"
