name: Run tests

on:
  workflow_call:
    inputs:
      code_directory:
        required: false
        type: string
        default: 'code'
      tools_directory:
        required: false
        type: string
        default: 'tools'
      matlab_release:
        required: false
        type: string
        default: 'latest'        

    secrets:
      commit_email_address:
        required: true
      CODECOV_TOKEN:
        required: false

jobs:
  # This workflow contains a single job called "test"
  test:
    name: Test toolbox code
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: # Assign secret to env to be able to use it in if: conditional below
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out the repository under $GITHUB_WORKSPACE, so the job can access it
      # Check out the head-ref if PR, as we are going to push badges back to the PR branch
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      
      - name: Set up MATLAB (${{ inputs.matlab_release }})
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ inputs.matlab_release }}

      # Check for MATLAB code issues in the project.
      - name: Check for MATLAB code issues
        uses: matlab-actions/run-command@v2
        if: always()
        with:
          command: |
            addpath(genpath( "${{ inputs.tools_directory }}" ));
            codecheckToolbox()

      # Upload code issues report
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: docs/reports/code_issues.sarif
      
      # Runs all tests in the project.
      - name: Run tests
        uses: matlab-actions/run-command@v2
        if: always()
        with:
          command: |
            addpath(genpath( "${{ inputs.tools_directory }}" ));
            testToolbox()

      # Commit updated SVG badges for the issues and tests (if changed)
      - name: Commit SVG badges if updated
        if: always()
        continue-on-error: true
        run: |
          git config user.name "${{ github.workflow }} by ${{ github.actor }}"
          git config user.email "${{ secrets.commit_email_address }}"
          git fetch 

          if [[ $(git add .github/badges/* --dry-run | wc -l) -gt 0 ]]; then
            git add .github/badges/*
            git commit -m "Update code issues and tests badges"
            git push -f
          else
            echo "Nothing to commit"
          fi

      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v4
        if: ${{ env.CODECOV_TOKEN != '' }}
        with:
          token: ${{ env.CODECOV_TOKEN }}
          files: docs/reports/codecoverage.xml
          
      # Publish test results
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "docs/reports/test-results.xml"
          
      # Save the contents of the reports directory as an artifact
      - name: Save reports directory
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: docs/reports
