name: Run codespell

on:
  workflow_call:
    inputs:
      config_file:
        required: false
        type: string
        default: '.codespellrc'

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    env:
      CONFIG_FILE: ${{ inputs.config_file }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract codespell configurations from configuration file
        id: config
        run: |
          # Extract 'skip' value from the config file, excluding 'skip = ' part
          skip=$(grep -E '^skip' "$CONFIG_FILE" | sed 's/^skip *= *//')
          
          # Extract 'ignore-words-list' value from the config file, excluding 'ignore-words-list = ' part
          ignore_words=$(grep -E '^ignore-words-list' "$CONFIG_FILE" | sed 's/^ignore-words-list *= *//')
          
          # Export values as environment variables
          echo "SKIP=$skip" >> $GITHUB_ENV
          echo "IGNORE_WORDS_LIST=$ignore_words" >> $GITHUB_ENV

      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: "${{ env.SKIP }}"
          ignore_words_list: "${{ env.IGNORE_WORDS_LIST }}"
