name: Run tests

on:
  workflow_call:
    inputs:
      code_directory:
        type: string
        default: 'code'
      tools_directory:
        type: string
        default: 'tools'
      matlab_release:
        type: string
        default: 'latest'
      matlab_use_cache:
        type: boolean
        default: false
      matlab_products:
        type: string
        default: ''

    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  # This workflow contains a single job called "test"
  test:
    name: Test toolbox code
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: # Assign secret to env to be able to use it in "if:" conditional below
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB (${{ inputs.matlab_release }})
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ inputs.matlab_release }}
          cache: ${{ inputs.matlab_use_cache }}
          products: ${{ inputs.matlab_products }}

      - name: Install MatBox
        uses: ehennestad/matbox/.github/actions/install-matbox@add-reusable-test-workflow

      - name: Check code and upload report
        uses: ehennestad/matbox/.github/actions/check-code@add-reusable-test-workflow
        with:
          code_directory: '.'
      
      - name: Run tests
        uses: ehennestad/matbox/.github/actions/test-code@add-reusable-test-workflow
        with:
          code_directory: ${{ inputs.code_directory }}
          tools_directory: ${{ inputs.tools_directory }}

      - name: Commit SVG badges if updated
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: ehennestad/matbox/.github/actions/push-badges@add-reusable-test-workflow
        with:
          pr-ref: ${{ github.event.pull_request.head.ref }}
          pr-repo: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v4
        if: ${{ env.CODECOV_TOKEN != '' }}
        with:
          token: ${{ env.CODECOV_TOKEN }}
          files: docs/reports/codecoverage.xml

      - name: Save reports directory
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: docs/reports
