name: Analyse code

on:
  workflow_call:
    inputs:
      code_directory:
        type: string
        default: 'code'
      tools_directory:
        type: string
        default: 'tools'
      matlab_release:
        type: string
        default: 'latest'

jobs:
  # This workflow contains a single job called "check"
  check:
    name: Check code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up MATLAB (${{ inputs.matlab_release }})
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ inputs.matlab_release }}
          cache: true

      - name: Install MatBox
        uses: ehennestad/matbox/.github/actions/install-matbox@add-reusable-test-workflow

      - name: Check code and upload report
        uses: ehennestad/matbox/.github/actions/check-code@add-reusable-test-workflow
        with:
          code_directory: ${{ inputs.code_directory }}
          tools_directory: ${{ inputs.tools_directory }}
      
      - name: Commit SVG badges if updated
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: ehennestad/matbox/.github/actions/push-badges@add-reusable-test-workflow
        with:
          pr-ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}
          pr-repo: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || github.repository }}
