name: Analyse code

on:
  workflow_call:
    inputs:
      code_directory:
        required: false
        type: string
        default: 'code'
      tools_directory:
        required: false
        type: string
        default: 'tools'
      matlab_release:
        required: false
        type: string
        default: 'latest'

    secrets:
      commit_email_address:
        required: true

jobs:
  # This workflow contains a single job called "check"
  check:
    name: Check code
    runs-on: ubuntu-22.04 # bump to latest when setup-matlab #146 is fixed

    steps:
      # Check out the repository under $GITHUB_WORKSPACE, so the job can access it
      # Check out the head-ref if PR, as we are going to push badges back to the PR branch
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

      - name: Set up MATLAB (${{ inputs.matlab_release }})
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ inputs.matlab_release }}

      - name: Install MatBox
        uses: ehennestad/matbox/.github/actions/install-matbox@add-reusable-test-workflow

      - name: Check code and upload report
        uses: ehennestad/matbox/.github/actions/check-code@add-reusable-test-workflow
        with:
          code_directory: ${{ inputs.code_directory }}
          tools_directory: ${{ inputs.tools_directory }}
      
      # Commit updated SVG badges for the issues (if changed)
      - name: Commit SVG badges if updated
        if: always()
        continue-on-error: true
        run: |
          git config user.name "${{ github.workflow }} by ${{ github.actor }}"
          git config user.email "${{ secrets.commit_email_address }}"
          git fetch 

          if [[ $(git add .github/badges/* --dry-run | wc -l) -gt 0 ]]; then
            git add .github/badges/*
            git commit -m "Update code issues badge"
            git push -f
          else
            echo "Nothing to commit"
          fi
