name: Run tests

on:
  # Triggers the workflow on push to any branch other than main or PR to main
  # This way tests will run on any push to a feature branch and when feature 
  # branches are merged to main, but not repeated when PRs are actually merged. 
  push:
    branches-ignore: ["main", "gh-badges"]
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
      - '.github/badges/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
      - '.github/badges/**'

  # Allows for manually running this workflow from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow-test-toolbox:
    name: Test toolbox code
    uses: ehennestad/matbox/.github/workflows/reusable_test_workflow.yml@v0.9
    with:
      matlab_use_cache: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
